version: '3.1'

services:
  book_pg:
    image: postgres:15.1
    container_name: book_pg
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: ubook
      POSTGRES_PASSWORD: secret123456
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
